# Generated by Django 4.1.7 on 2023-02-17 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userProfileImage', models.ImageField(blank=True, null=True, upload_to='userProfileImgs/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('NA', 'NA')], default='NA', max_length=45)),
                ('auth_token', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
